FORMAT: 1A
HOST: http://127.0.0.1:2330/project/public/

# 哔谱哔谱(Bipubipu) API

本系统提供曲谱分享系统系列接口。

## 注意

所有非白名单请求(需要权限的请求), 都必须传递 `username`, `sign` 和 `timestamp` 三个参数. 

其中 `timestamp` 为 unix 时间戳, 单位为秒.

其中 `sign` 为请求签名, 其算法为 `sha1(timestamp + username + token)`.

签名算法中, `token` 为登录凭证, 在邮箱登录成功后下发. 有效期 30 天.



统一返回格式为:

```json
{
    "ret": xxx,
    "data": {},
    "msg": ""
}
```
如果操作成功, 则 `ret` 为 200. `msg` 为空. 否则 `ret` 为错误码, `msg` 为错误提示.

## 会话验证类 [/auth]

### 发送邮箱验证码 [POST /auth/captch/email]

调用之后, 会向用户邮箱发送一个六位数的验证码. 不检查邮箱存在性. 已注册的用户也可以接收验证码.

如果距离上次发送时间不到 60s, 则不允许发送验证码. 防止高频提交

验证码的过期时间为 15min.

**应用场景** 注册/异常登录验证/找回密码/更改密码/注销

+ Attributes
    + email: xiaoming@gmail.com (string) - 邮件地址

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)

        {
            "ret": 200,
            "data": {},
            "msg": ""
        }
        

### 通过邮箱注册 [POST /auth/register/email]

唯一需要提供明文密码的 API.

+ Attributes
    + email: xiaoming@gmail.com (string) - 邮件地址
    + username: xiaoming (string) - 用户名
    + captch: 141592 (string) - 验证码
    + passowrd: fdsfFAD9f43f2 (string) - 明文密码

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)

        {
            "ret": 200,
            "data": {},
            "msg": ""
        }

### 获得登录随机串 [POST /auth/nonce]

获取 nonce (有效期为30s), 以用于避免重放攻击, 保证登录安全性.

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)

        {
            "ret": 200,
            "data": {
                "nonce": "defd2d3f5587c5239946eb740100d62bfae690fe"
            },
            "msg": ""
        }
        


### 通过邮箱登录 [POST /auth/login/email]

登录过程:

1. 用户从服务器获取一个随机串 nonce。服务器保存 nouce+timestamp
2. 用户计算 `sign = sha1(nonce.email.sha1('moeje'.password))`.
3. 提交 sign, email, nonce
4. 服务器判断 nonce 是否过期, 如果没过期, 继续进行其他验证
4. 登录成功，得到 token（有效期为30天，若主动注销则立刻过期）。
5. 利用 token 可以实现免登录。

**注意:** 此处的 sign 为登录专用, 其它请求的 sign 的算法为: `sha1(timestamp + username + token)`

+ Attributes
    + email: xiaoming@gmail.com (string) - 邮件地址
    + nonce: defd2d3f5587c5239946eb740100d62bfae690fe (string) - 随机串
    + sign: 718a150f4697594ffd8463d8b5347b5c847c2718 (string) - 签名

+ Request (application/x-www-form-urlencoded)

+ Response 200 (application/json)

        {
            "ret": 200,
            "data": {
                "id": "5684891",
                "username": "xiaoming",
                "email": "xiaoming@gmail.com",
                "phone": null,
                "token": "9196f17654c9275740e5075d5e7b0a609b308139",
                "group": [{
                    "id": "1",
                    "rules": "1,1101,301,302,303,304,305,306"
                }]
            },
            "msg": ""
        }

